### ISSUE TITLE
[souremation/strimzi-kafka-operator]

### ISSUE THREAD

**Issue by qwiatu-lp** [SourceMation/charts#73]
### Short bug description

The Kafka operator doesn't deploy the Kafka cluster in a namespace different from the operator's namespace

### Chart name and version

sourcemation/strimzi-kafka-operator-0.1.1

### Architecture used

amd64

### Steps to reproduce the bug

1. deploy operator
2. deploy example kafka cluster in kraft mode different than operator
3. cluster do not deploy

```
export K8S_NAMESPACE=moj-namespace
export KAFKA_CLUSTER_NAME=kawusia
 
kubectl apply -f - <<EOF
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  namespace: ${K8S_NAMESPACE}
  labels:
    strimzi.io/cluster: ${KAFKA_CLUSTER_NAME}
spec:
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
#    volumes:
#      - id: 0
#        type: persistent-claim
#        size: 5Gi
#        kraftMetadata: shared
#        deleteClaim: false
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  namespace: ${K8S_NAMESPACE}
  labels:
    strimzi.io/cluster: ${KAFKA_CLUSTER_NAME}
spec:
  replicas: 3
  roles:
    - broker
  storage:
    type: jbod
#    volumes:
#      - id: 0
#        type: persistent-claim
#        size: 5Gi
#        kraftMetadata: shared
#        deleteClaim: false
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ${KAFKA_CLUSTER_NAME}
  namespace: ${K8S_NAMESPACE}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
EOF
```

### Expected behavior

Run kafka cluster in different namespace
```
strimzi-kafka-operator:
  watchAnyNamespace: true
```

### Actual result

no errors
